### ISSUE TITLE
[Labctrl] Fix data saver overwriting mode attributes

### ISSUE THREAD

**Issue by ktnc985** [Qcrew/labctrl#2]

**Comment by atharvjoshi** [comment]
Commit f462fe1dde33ec2e12ce3b752fd7ed2ea6aea138.
Completed initial testing of the new DataSaver - its dataset specification protocol, context manager, save_data() and save_metadata() methods. These changes should fix the overwriting mode attributes issue - will only know for sure once we test it with real-world data. For now, we can close this issue.
